name: 'Prepare MSYS2'
description: 'Prepare MSYS2 environment'
runs:
  using: composite
  steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-nsis
          mingw-w64-x86_64-poppler
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-toolchain
