name: build-focal-gcc
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    steps:
      - uses: actions/checkout@v2
        with:
          path: vpdf
      - run: cmake -S vpdf
                   -B vpdf-build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_PREFIX_PATH="${QT_PREFIX}"
      - run: cmake --build vpdf-build
                   --config Release
                   -j4
